spring:
    data:
      # mongodb:
      #     #host: 192.168.0.18
      #     database: mydb
      #     port: 27017
      rest:
          basePath: /api
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 216541841652-9sdtnoa38mb0h07rlp3dijnrk32s7l4v.apps.googleusercontent.com
              clientSecret: pVJGK67vP6DhxgKSGrMG-3YT
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 121189305185277
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
            customClient:
              client-id: R2dpxQ3vPrtfgF72
              client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
              client-name: Auth Server
              scope: user_info
              provider: custom-provider
              redirect-uri: "{baseUrl}/oauth2/callback/customClient"
              # clientAuthenticationMethod: basic
              authorization-grant-type: authorization_code
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
            custom-provider:
              token-uri: http://localhost:8081/auth/oauth/token
              authorization-uri: http://localhost:8081/auth/oauth/authorize
              user-info-uri: http://localhost:8081/auth/user/me
              user-name-attribute: name

  
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect